CREATE DATABASE IF NOT EXISTS exercices;

use exercices;

CREATE TABLE exercice (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nom VARCHAR(255) DEFAULT NULL,
    marks VARCHAR(50) DEFAULT NULL,
    set1 VARCHAR(255) DEFAULT NULL,
    set2 VARCHAR(50) DEFAULT NULL,
    set3 VARCHAR(50) DEFAULT NULL,
    set4 VARCHAR(50) DEFAULT NULL 
    description TEXT DEFAULT NULL,  
    PRIMARY KEY (id)
);
